import { createClient } from "@/lib/supabase/client";
import { eventBus } from "@/lib/events/EventBus";

export const DEFAULT_WAREHOUSE_ID = "wh_main";
export type MovementType = "receive" | "deduct" | "return" | "transfer_in" | "transfer_out" | "adjustment";
export type MovementReferenceType = "purchase_receipt" | "order" | "return" | "transfer" | "adjustment" | "initial";
export interface InventoryMovement { id: string; productId: string; productName?: string; variantId?: string; type: MovementType; quantity: number; balanceBefore: number; balanceAfter: number; reason: string; referenceType?: MovementReferenceType; referenceId?: string; warehouseId?: string; date: string; userId: string; }
export interface InventoryAlert { productId: string; variantId?: string; productName: string; variantName?: string; currentStock: number; threshold: number; }
export interface InventoryStats { totalProducts: number; inStock: number; lowStock: number; outOfStock: number; inventoryValue: number; }
export interface RecordMovementInput { productId: string; variantId?: string; type: MovementType; quantity: number; reason: string; referenceType?: MovementReferenceType; referenceId?: string; warehouseId?: string; userId?: string; }

type MovementRow = Record<string, unknown> & { products?: { name?: string } | null };
function map(row: MovementRow): InventoryMovement { return { id: String(row.id), productId: String(row.product_id), productName: row.products?.name, variantId: row.variant_id ? String(row.variant_id) : undefined, type: String(row.movement_type) as MovementType, quantity: Number(row.quantity), balanceBefore: Number(row.balance_before), balanceAfter: Number(row.balance_after), reason: String(row.reason), referenceType: row.reference_type as MovementReferenceType | undefined, referenceId: row.reference_id ? String(row.reference_id) : undefined, warehouseId: DEFAULT_WAREHOUSE_ID, date: String(row.created_at), userId: String(row.created_by ?? "system") }; }

export const InventoryService = {
  async getMovements(productId?: string): Promise<InventoryMovement[]> { let query = createClient().from("stock_movements").select("*, products(name)").order("created_at", { ascending: false }); if (productId) query = query.eq("product_id", productId); const { data, error } = await query; if (error) throw new Error(error.message); return ((data ?? []) as MovementRow[]).map(map); },
  async getMovement(id: string) { const { data, error } = await createClient().from("stock_movements").select("*, products(name)").eq("id", id).maybeSingle(); if (error) throw new Error(error.message); return data ? map(data as MovementRow) : undefined; },
  async getMovementsByReference(referenceType: MovementReferenceType, referenceId: string) { const { data, error } = await createClient().from("stock_movements").select("*, products(name)").eq("reference_type", referenceType).eq("reference_id", referenceId); if (error) throw new Error(error.message); return ((data ?? []) as MovementRow[]).map(map); },
  async recordMovement(input: RecordMovementInput) { const { data, error } = await createClient().rpc("adjust_inventory", { target_product_id: input.productId, target_variant_id: input.variantId ?? null, quantity_change: input.quantity, movement_reason: input.reason, movement_kind: input.type, ref_type: input.referenceType ?? null, ref_id: input.referenceId ?? null }); if (error) throw new Error(error.message); const movement = await this.getMovement(String(data)); if (!movement) throw new Error("Không thể tải phiếu kho vừa tạo."); eventBus.emit("inventory.changed"); return movement; },
  async receiveStock(productId: string, quantity: number, reason: string, ref?: { type: MovementReferenceType; id: string }) { return this.recordMovement({ productId, type: "receive", quantity: Math.abs(quantity), reason, referenceType: ref?.type, referenceId: ref?.id }); },
  async deductStock(productId: string, quantity: number, reason: string, ref?: { type: MovementReferenceType; id: string }) { return this.recordMovement({ productId, type: "deduct", quantity: -Math.abs(quantity), reason, referenceType: ref?.type, referenceId: ref?.id }); },
  async adjustStock(productId: string, variantId: string | undefined, quantityChange: number, reason: string) { return this.recordMovement({ productId, variantId, type: "adjustment", quantity: quantityChange, reason, referenceType: "adjustment" }); },
  async updateMovement(id: string, changes: { quantity?: number; reason?: string }) { const current = await this.getMovement(id); if (!current) throw new Error("Không tìm thấy phiếu kho."); const { error } = await createClient().rpc("edit_stock_movement", { target_movement_id: id, new_quantity: changes.quantity ?? current.quantity, new_reason: changes.reason ?? current.reason }); if (error) throw new Error(error.message); const updated = await this.getMovement(id); if (!updated) throw new Error("Không tìm thấy phiếu kho."); eventBus.emit("inventory.changed"); return updated; },
  async deleteMovement(id: string) { const { error } = await createClient().rpc("delete_stock_movement", { target_movement_id: id }); if (error) throw new Error(error.message); eventBus.emit("inventory.changed"); },
  async reverseMovement(id: string, reason: string) { const { data, error } = await createClient().rpc("reverse_stock_movement", { target_movement_id: id, reversal_reason: reason }); if (error) throw new Error(error.message); eventBus.emit("inventory.changed"); return this.getMovement(String(data)); },
  async getLowStockAlerts(threshold?: number): Promise<InventoryAlert[]> { const { data, error } = await createClient().from("products").select("id,name,stock,low_stock_limit").eq("status", "published"); if (error) throw new Error(error.message); const products = (data ?? []) as Array<{ id: string; name: string; stock: number; low_stock_limit: number }>; return products.filter((product) => Number(product.stock) <= (threshold ?? Number(product.low_stock_limit))).map((product) => ({ productId: product.id, productName: product.name, currentStock: Number(product.stock), threshold: threshold ?? Number(product.low_stock_limit) })); },
  getInventoryValue() { return 0; },
  getStats(): InventoryStats { return { totalProducts: 0, inStock: 0, lowStock: 0, outOfStock: 0, inventoryValue: 0 }; },
};
