import { createClient } from "@/lib/supabase/client";
import { eventBus } from "@/lib/events/EventBus";

export interface Review { id: string; productId: string; productName: string; productImage: string; customerId?: string; customerName: string; customerEmail: string; customerAvatar?: string; rating: number; title: string; content: string; status: "pending" | "approved" | "rejected" | "hidden"; isFeatured: boolean; isPinned: boolean; verifiedPurchase: boolean; adminReply: string | null; createdAt: string; updatedAt: string; }
type Row = Record<string, unknown> & { products?: { name?: string; product_images?: Array<{ url: string; sort_order: number }> } | null };
const select = "*, products(name, product_images(url, sort_order))";
function map(row: Row): Review { const images = [...(row.products?.product_images ?? [])].sort((a, b) => a.sort_order - b.sort_order); return { id: String(row.id), productId: String(row.product_id), productName: row.products?.name ?? "Sản phẩm Soft Muse", productImage: images[0]?.url ?? "", customerId: row.customer_id ? String(row.customer_id) : undefined, customerName: String(row.customer_name), customerEmail: String(row.customer_email ?? ""), customerAvatar: row.customer_avatar ? String(row.customer_avatar) : undefined, rating: Number(row.rating), title: String(row.title ?? ""), content: String(row.content), status: String(row.status) as Review["status"], isFeatured: Boolean(row.is_featured), isPinned: Boolean(row.is_pinned), verifiedPurchase: Boolean(row.verified_purchase), adminReply: row.admin_reply ? String(row.admin_reply) : null, createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }

export const ReviewService = {
  async getReviews(filters?: { status?: Review["status"]; productId?: string; isFeatured?: boolean }): Promise<Review[]> { let query = createClient().from("reviews").select(select).order("created_at", { ascending: false }); if (filters?.status && filters.status !== "hidden") query = query.eq("status", filters.status); if (filters?.productId) query = query.eq("product_id", filters.productId); if (filters?.isFeatured !== undefined) query = query.eq("is_featured", filters.isFeatured); const { data, error } = await query; if (error) throw new Error(error.message); return ((data ?? []) as Row[]).map(map); },
  getReviewsSync(): Review[] { return []; },
  async getReview(id: string) { const { data, error } = await createClient().from("reviews").select(select).eq("id", id).maybeSingle(); if (error) throw new Error(error.message); return data ? map(data as Row) : null; },
  async createReview(input: Omit<Review, "id" | "createdAt" | "updatedAt" | "isFeatured" | "isPinned" | "adminReply">) { const { data, error } = await createClient().from("reviews").insert({ product_id: input.productId, customer_id: input.customerId ?? null, customer_name: input.customerName, customer_email: input.customerEmail, customer_avatar: input.customerAvatar ?? null, rating: input.rating, title: input.title, content: input.content, status: "pending", verified_purchase: input.verifiedPurchase }).select(select).single(); if (error) throw new Error(error.message); const review = map(data as Row); eventBus.emit("reviews.changed"); return review; },
  async updateReviewStatus(id: string, status: Review["status"]) { const dbStatus = status === "hidden" ? "rejected" : status; const { data, error } = await createClient().from("reviews").update({ status: dbStatus }).eq("id", id).select(select).single(); if (error) throw new Error(error.message); eventBus.emit("reviews.changed"); return map(data as Row); },
  async updateAdminReply(id: string, reply: string | null) { return this.updateReview(id, { adminReply: reply } as never); },
  async toggleFeatured(id: string) { const review = await this.getReview(id); if (!review) throw new Error("Không tìm thấy đánh giá."); const { data, error } = await createClient().from("reviews").update({ is_featured: !review.isFeatured }).eq("id", id).select(select).single(); if (error) throw new Error(error.message); eventBus.emit("reviews.changed"); return map(data as Row); },
  async togglePinned(id: string) { const review = await this.getReview(id); if (!review) throw new Error("Không tìm thấy đánh giá."); const { data, error } = await createClient().from("reviews").update({ is_pinned: !review.isPinned }).eq("id", id).select(select).single(); if (error) throw new Error(error.message); eventBus.emit("reviews.changed"); return map(data as Row); },
  async updateReview(id: string, updates: Partial<Pick<Review, "title" | "content" | "customerAvatar" | "verifiedPurchase" | "adminReply">>) { const { data, error } = await createClient().from("reviews").update({ title: updates.title, content: updates.content, customer_avatar: updates.customerAvatar, verified_purchase: updates.verifiedPurchase, admin_reply: updates.adminReply }).eq("id", id).select(select).single(); if (error) throw new Error(error.message); eventBus.emit("reviews.changed"); return map(data as Row); },
  async deleteReview(id: string) { const { error } = await createClient().from("reviews").delete().eq("id", id); if (error) throw new Error(error.message); eventBus.emit("reviews.changed"); },
};
